version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: line-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: line-frontend
    ports:
      - "80:80"
